require("packs/reload")
require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("packs/main")
require("packs/ajax")
require("packs/onchange")
require("jquery")
require("packs/scroll")
require("cocoon-js")
require("packs/order_status")
require("packs/plugins")
require("packs/vendor/bootstrap")
require("packs/vendor/bootstrap.min")
require("packs/jquery-1.12.4")
require("packs/jquery-ui")
import toastr from 'toastr'
window.toastr = toastr
